import type { QuestDevQuestion } from '../../models/quest-dev.models';

export const THEORIC_TESTING_QUALITY_QUESTIONS: QuestDevQuestion[] = [
  {
    id: 'th-test-01',
    topic: 'Dobles de prueba',
    prompt: {
      es: '¿Cuál es la diferencia entre un stub y un mock?',
      en: 'What is the difference between a stub and a mock?',
    },
    answer: {
      es: 'El stub provee respuestas predefinidas; el mock además verifica que se le haya llamado como se esperaba.',
      en: 'A stub provides canned answers; a mock additionally verifies it was called as expected.',
    },
    distractors: [
      {
        es: 'El stub se escribe a mano y el mock lo genera una librería como Mockito o Jasmine.',
        en: 'A stub is hand-written while a mock is generated by a library such as Mockito or Jasmine.',
      },
      {
        es: 'El stub reemplaza dependencias externas y el mock reemplaza la clase bajo prueba para aislar sus métodos.',
        en: 'A stub replaces external dependencies while a mock replaces the class under test to isolate its methods.',
      },
    ],
    explanation: {
      es: 'La distinción es de verificación: el stub soporta la prueba de estado (qué devolvió el sistema) y el mock la prueba de interacción (qué mensajes envió). Cómo se construye el doble es irrelevante para la clasificación, y nunca se sustituye la clase bajo prueba: eso dejaría la prueba sin sujeto.',
      en: 'The distinction is about verification: a stub supports state testing (what the system returned) and a mock supports interaction testing (which messages it sent). How the double is built is irrelevant to the classification, and you never replace the class under test: that would leave the test without a subject.',
    },
  },
  {
    id: 'th-test-02',
    topic: 'Pirámide de pruebas',
    prompt: {
      es: 'Según la pirámide de pruebas, ¿qué implica tener muchas pruebas end-to-end y pocas unitarias?',
      en: 'According to the test pyramid, what does having many end-to-end tests and few unit tests imply?',
    },
    answer: {
      es: 'Una suite lenta y frágil que además señala mal dónde está el fallo (antipatrón del cono de helado).',
      en: 'A slow, brittle suite that also points poorly to where the failure is (ice-cream cone anti-pattern).',
    },
    distractors: [
      {
        es: 'Mayor confianza global, con el único costo de un pipeline de integración continua más lento.',
        en: 'Higher overall confidence, with the only cost being a slower continuous integration pipeline.',
      },
      {
        es: 'Una cobertura de código inflada, porque las pruebas end-to-end no reportan líneas ejecutadas.',
        en: 'Inflated code coverage, because end-to-end tests do not report executed lines.',
      },
    ],
    explanation: {
      es: 'El problema no es solo la duración: las pruebas E2E fallan por causas ajenas (red, datos, timing), producen falsos positivos que erosionan la confianza del equipo y, cuando fallan, no dicen qué unidad se rompió. Las E2E sí pueden instrumentarse para medir cobertura, así que el problema tampoco es la métrica.',
      en: 'The problem is not only duration: E2E tests fail for unrelated reasons (network, data, timing), produce flaky results that erode team trust and, when they fail, do not tell which unit broke. E2E runs can be instrumented for coverage, so the metric is not the issue either.',
    },
  },
  {
    id: 'th-test-03',
    topic: 'TDD',
    prompt: {
      es: 'En el ciclo rojo-verde-refactor, ¿qué se hace en la fase verde?',
      en: 'In the red-green-refactor cycle, what happens during the green phase?',
    },
    answer: {
      es: 'Escribir el código más simple que haga pasar la prueba, aunque sea imperfecto.',
      en: 'Write the simplest code that makes the test pass, even if it is imperfect.',
    },
    distractors: [
      {
        es: 'Escribir la implementación definitiva y limpia, para que el refactor posterior solo ajuste nombres.',
        en: 'Write the final, clean implementation so the later refactor only adjusts names.',
      },
      {
        es: 'Agregar las pruebas de los casos borde que faltan antes de pasar a la fase de refactor.',
        en: 'Add the missing edge-case tests before moving on to the refactor phase.',
      },
    ],
    explanation: {
      es: 'La fase verde busca cerrar el ciclo rápido: incluso devolver una constante es válido, porque la deuda se paga en el refactor con la red de seguridad ya puesta. Intentar escribir la solución definitiva antes de tener la prueba en verde mezcla las fases, y agregar nuevas pruebas abre un ciclo rojo distinto.',
      en: 'The green phase is about closing the loop fast: even returning a constant is valid, because the debt is paid during refactor with the safety net already in place. Trying to write the final solution before the test is green mixes the phases, and adding new tests opens a different red cycle.',
    },
  },
  {
    id: 'th-test-04',
    topic: 'Cobertura',
    prompt: {
      es: 'Un módulo tiene 95% de cobertura de líneas y aun así aparecen errores en producción. ¿Cuál es la explicación más probable?',
      en: 'A module has 95% line coverage and still produces production bugs. What is the most likely explanation?',
    },
    answer: {
      es: 'La cobertura mide líneas ejecutadas, no aserciones útiles ni combinaciones de ramas y casos borde.',
      en: 'Coverage measures executed lines, not meaningful assertions or branch and edge-case combinations.',
    },
    distractors: [
      {
        es: 'Falta llegar al 100%, porque el 5% restante concentra estadísticamente la mayoría de los defectos.',
        en: 'It has not reached 100%, because the remaining 5% statistically holds most of the defects.',
      },
      {
        es: 'Las pruebas unitarias no cuentan para la cobertura real, que solo se mide con pruebas de integración.',
        en: 'Unit tests do not count toward real coverage, which is only measured with integration tests.',
      },
    ],
    explanation: {
      es: 'Una prueba puede recorrer una línea sin verificar nada, y la cobertura de líneas ignora la explosión combinatoria de condiciones (de ahí métricas como cobertura de ramas o pruebas de mutación). Perseguir el 100% es un objetivo de vanidad y el tipo de prueba no cambia cómo se instrumenta la métrica.',
      en: 'A test can execute a line without asserting anything, and line coverage ignores the combinatorial explosion of conditions (hence metrics like branch coverage or mutation testing). Chasing 100% is a vanity target, and the test type does not change how the metric is instrumented.',
    },
  },
  {
    id: 'th-test-05',
    topic: 'Pruebas',
    prompt: {
      es: '¿Qué caracteriza a una prueba unitaria bien diseñada?',
      en: 'What characterises a well-designed unit test?',
    },
    answer: {
      es: 'Es determinista, independiente del orden de ejecución y verifica comportamiento observable, no detalles internos.',
      en: 'It is deterministic, independent of execution order and verifies observable behaviour rather than internals.',
    },
    distractors: [
      {
        es: 'Cubre una sola clase reemplazando con dobles absolutamente todas sus colaboraciones.',
        en: 'It covers a single class by replacing absolutely all of its collaborations with doubles.',
      },
      {
        es: 'Contiene una sola aserción, de modo que cada fallo identifique exactamente una causa.',
        en: 'It contains a single assertion, so each failure identifies exactly one cause.',
      },
    ],
    explanation: {
      es: 'El criterio central es el aislamiento respecto a otras pruebas y el foco en el contrato: una prueba atada a internos se rompe en cada refactor legítimo. Mockear todo, incluidos objetos de valor, produce pruebas que solo verifican la implementación; y "una aserción por prueba" es una guía de estilo, no un requisito, siempre que todas validen el mismo comportamiento.',
      en: 'The core criterion is isolation from other tests plus focus on the contract: a test tied to internals breaks on every legitimate refactor. Mocking everything, including value objects, yields tests that only verify the implementation; and "one assertion per test" is a style guideline, not a requirement, as long as all assertions validate the same behaviour.',
    },
  },
  {
    id: 'th-test-06',
    topic: 'Pruebas de integración',
    prompt: {
      es: '¿Cuál es el valor principal de las pruebas de contrato entre dos servicios?',
      en: 'What is the main value of contract tests between two services?',
    },
    answer: {
      es: 'Verificar que consumidor y proveedor comparten expectativas sin necesidad de desplegar ambos juntos.',
      en: 'Verify that consumer and provider share expectations without having to deploy both together.',
    },
    distractors: [
      {
        es: 'Validar el rendimiento del proveedor bajo la carga real que genera cada consumidor registrado.',
        en: 'Validate provider performance under the real load generated by each registered consumer.',
      },
      {
        es: 'Reemplazar la documentación de la API, porque el contrato se genera a partir del código del proveedor.',
        en: 'Replace API documentation, because the contract is generated from the provider code.',
      },
    ],
    explanation: {
      es: 'Con pruebas de contrato (por ejemplo Pact), el consumidor declara qué espera y el proveedor verifica ese contrato en su propio pipeline, detectando rupturas sin un entorno de integración compartido. No miden rendimiento, y aunque el contrato sirva como documentación viva, en el enfoque consumer-driven lo define el consumidor.',
      en: 'With contract tests (for example Pact), the consumer declares what it expects and the provider verifies that contract in its own pipeline, catching breaking changes without a shared integration environment. They do not measure performance, and although the contract works as living documentation, in the consumer-driven approach the consumer defines it.',
    },
  },
  {
    id: 'th-test-07',
    topic: 'Calidad',
    prompt: {
      es: '¿Qué describe la deuda técnica en su sentido original?',
      en: 'What does technical debt describe in its original sense?',
    },
    answer: {
      es: 'El costo futuro de haber elegido una solución rápida en lugar de la más adecuada, que se paga con intereses.',
      en: 'The future cost of having chosen a quick solution instead of the most suitable one, repaid with interest.',
    },
    distractors: [
      {
        es: 'El conjunto de defectos conocidos y tareas pendientes acumuladas en el backlog del equipo.',
        en: 'The set of known defects and pending tasks accumulated in the team backlog.',
      },
      {
        es: 'La obsolescencia natural de librerías y frameworks que exige actualizaciones periódicas.',
        en: 'The natural obsolescence of libraries and frameworks that demands periodic upgrades.',
      },
    ],
    explanation: {
      es: 'La metáfora de Ward Cunningham habla de una decisión consciente de diseño que permite entregar antes, con el compromiso de refactorizar; el interés es la fricción creciente en cada cambio posterior. Los bugs pendientes son bugs, y quedarse atrás en versiones es un caso particular, no la definición.',
      en: 'Ward Cunningham metaphor is about a conscious design decision that allows shipping sooner, with a commitment to refactor; the interest is the growing friction on every later change. Pending bugs are bugs, and falling behind on versions is a particular case, not the definition.',
    },
  },
];
